import Link from 'next/link'
export const metadata = {
  title: 'Day 6: The Enema, the Standoff, and the Temple Behind the Bodega',
  description: 'Day 6 of a Kerala Ayurvedic retreat — refusing the treatment, the first time leaving the property, a hidden temple, a new friend, and anxiety about going home.',
}
export default function RetreatDay6Page() {
  return (
    <main style={{maxWidth: "680px", margin: "0 auto", padding: "48px 24px"}}>
      <article>
        <header style={{marginBottom: "48px"}}>
          <p style={{fontSize: "14px", color: "#8c7b6b", marginBottom: "8px"}}>May 30, 2026 &middot; Ayurvedic Retreat, Day 6</p>
          <h1 style={{fontSize: "36px", fontWeight: "700", lineHeight: "1.2", marginBottom: "16px"}}>Day 6: The Enema, the Standoff, and the Temple Behind the Bodega</h1>
          <p style={{fontSize: "14px", color: "#8c7b6b"}}>By Alex &middot; DoshaFlow</p>
        </header>
        <p>One and a half hours of sleep. That is my number for last night. My running total for this retreat is approximately one good night of sleep and everything else held together with stubbornness and spite. I want to be clear that this is entirely my own doing. The laptop is right there and I cannot leave it alone.</p>
        <h2 style={{fontSize: "22px", fontWeight: "700", marginTop: "48px", marginBottom: "16px"}}>9am: the enema.</h2>
        <p>I will not dwell on this. I will simply say that Ayurveda has views about internal cleansing, that those views are ancient and clinically grounded, and that this morning those views were applied to me at 9am while I was running on ninety minutes of sleep. It is fine. Everything is fine. Moving on.</p>
        <h2 style={{fontSize: "22px", fontWeight: "700", marginTop: "48px", marginBottom: "16px"}}>The standoff.</h2>
        <p>I woke up groggy in a way that felt personal. Not tired — affronted. My body was insulted. I had breakfast, ate my correctly-portioned meal without really tasting it, and made a decision: I was not doing the 11am treatment. The 11am treatment is an hour of lying still while someone works on you. On ninety minutes of sleep, still processing the morning&apos;s events, in a mood I would describe generously as not ready to be touched by another human being — the idea of lying there for sixty minutes while my brain ran its circuits felt unbearable. My doctor — who I like, who I trust — was off for the day. So I walked to the treatment centre and informed the covering doctor that I would not be participating. She disagreed. Firmly. I said, with the particular calm of someone running on fumes: I am not doing it. And I walked back to my room. They sent someone after me. I texted a few people. I thought, briefly and without real conviction, about how easy it would be to just leave. I did not leave. But I thought about it.</p>
        <h2 style={{fontSize: "22px", fontWeight: "700", marginTop: "48px", marginBottom: "16px"}}>The turn.</h2>
        <p>Lunch happened. The portion control situation continues to be one of the more unexpected experiences of this trip — I am eating less than I have in years and I feel sharper and more productive than I did at home with a full night&apos;s sleep and Adderall in my system. After lunch I decided, on my own terms, to go to the 2:15 massage. Nobody made me. The morning&apos;s refusal stood. The afternoon was different. Then yoga. I had seventeen good reasons to skip it. I went anyway. Three hours of sleep across two days, and I did the full class. I am not historically someone who pushes through things I do not want to do. But I have been doing it here, small win by small win, and something about that is starting to add up.</p>
        <h2 style={{fontSize: "22px", fontWeight: "700", marginTop: "48px", marginBottom: "16px"}}>The first time off the property.</h2>
        <p>At 6pm, the retreat arranged an optional temple visit — a chance to leave the compound for the first time since I arrived. The entire group who wanted to go turned out to be two people: me, and one other guest. He was a young Indian man who lives in Saudi Arabia. I had not spoken properly to anyone here since arriving. The driver took us to what appeared, from the car, to be a small neighbourhood grocery store. He parked. Got out. We sat there confused, assuming he was picking up a snack. He turned around and looked at us with an expression that said very clearly: what are you doing, get out of the car. We got out. He pointed to an alley behind the building. Down the alley, taking up maybe 300 or 400 square feet, was a temple. Brightly painted, run-down in the way certain places are run-down — not neglected, just old and worn in by decades of use. We went in. My new friend guided me through the protocol. We gave the priest our names. We could also give the name of someone we wanted to pray for. I gave my mother&apos;s name. They conducted a prayer. I am not someone who uses the word energy unironically. I am going to use it anyway: there was something in that room. Not mystical, not performative. Just the accumulated weight of a great many people bringing whatever they were carrying and leaving some of it there.</p>
        <h2 style={{fontSize: "22px", fontWeight: "700", marginTop: "48px", marginBottom: "16px"}}>Dinner.</h2>
        <p>We drove back and ended up having dinner together — my new friend, his mother who is also here at the retreat, and one other person. The food was the same retreat kitchen food I have been eating for six days, but eaten with company it tasted completely different. His mother had done this before. She said the weight loss everyone notices in the first week is just the beginning — the real changes come after you leave, if you keep the habits. She said it matter-of-factly, the way someone says something they have watched happen. I believed her.</p>
        <h2 style={{fontSize: "22px", fontWeight: "700", marginTop: "48px", marginBottom: "16px"}}>The number, and the anxiety about leaving.</h2>
        <p>Weight this morning: 162.5 pounds. Down a kilo from when I arrived. I have eight days left. That number hit differently tonight. Not because I want to stay — I want to sleep in my own bed desperately — but because I have started to feel the approach of everything I left behind, and I am not entirely sure I am ready to be back in proximity to it. I am getting anxious about alcohol. About going back into the world where it is everywhere and normal and social and easy. About whether what I have been building here is strong enough to hold once the context changes. I do not have a clean answer. What I have is that I did yoga today on ninety minutes of sleep when everything in me said not to. That is something. Sleep: 1.5 hours. Treatments: one afternoon massage. Yoga: done. Temple: visited. Kilos lost: one. Prayers given in my mother&apos;s name: one. New friends made: one, plus his mother. Days remaining: eight.</p>
        <div style={{marginTop: "48px", paddingTop: "32px", borderTop: "1px solid #e8e0d4"}}>
          <Link href="/quiz" style={{display: "inline-block", backgroundColor: "#b5763a", color: "white", padding: "12px 24px", borderRadius: "6px", textDecoration: "none", fontWeight: "600"}}>Take the Free Dosha Quiz</Link>
        </div>
      <ContinueJourney />
      </article>
    </main>
  )
}
