// Category-based accent colors for article heroes and filter pills.
// Keyed by the real topic categories in lib/categories.ts — one entry per
// category. These preserve the palette the blog used previously.

const DEFAULT_ACCENT = "#C97F3D"

export const CATEGORY_COLORS: Record<string, { accent: string; border: string; pill: string }> = {
  Doshas: { accent: "#8a7a6e", border: "#a09a8e", pill: "#f5f0e8" },
  Digestion: { accent: "#b5963a", border: "#c4a655", pill: "#faf8f2" },
  Sleep: { accent: "#7a8fa8", border: "#8fa3b8", pill: "#f0f4fa" },
  "Stress & Anxiety": { accent: "#8fa88e", border: "#a8b8a7", pill: "#f0f4f0" },
  "Weight Loss": { accent: "#8a9a55", border: "#a3b072", pill: "#f3f5ea" },
  "Skin & Hair": { accent: "#b57f7a", border: "#c99a95", pill: "#faf1ef" },
  "Body & Systems": { accent: "#5f938c", border: "#7fa9a2", pill: "#edf4f3" },
  Herbs: { accent: "#6f8f4a", border: "#88a366", pill: "#eff4e6" },
  Tea: { accent: "#9a8a5a", border: "#b0a070", pill: "#faf8f2" },
  "Daily Practices": { accent: "#8a7fa8", border: "#a396bd", pill: "#f2f0f7" },
  Editorial: { accent: "#a89a7a", border: "#b0a890", pill: "#faf7f0" },
  "Retreat Journal": { accent: "#b5763a", border: "#d4a574", pill: "#fdf6ee" },
}

// Accent color for a given category. Reads the category-keyed map above and
// falls back to the brand ochre for any unassigned/legacy value.
export function getCategoryColor(category: string): string {
  return CATEGORY_COLORS[category]?.accent ?? DEFAULT_ACCENT
}

// Map of articles with their highlight words
export const highlightMap: Record<string, string> = {
  "aging-gracefully": "Aging",
  "ashwagandha-benefits": "Ashwagandha",
  "ayurveda-30-days": "Ayurveda",
  "ayurveda-aging": "Aging",
  "ayurveda-alcohol": "Alcohol",
  "ayurveda-alcohol-recovery": "Recovery",
  "ayurveda-beginners-guide": "Ayurveda",
  "ayurveda-burnout": "Burnout",
  "ayurveda-coffee": "Coffee",
  "ayurveda-cold-smoothies": "Smoothies",
  "ayurveda-cortisol-stress": "Cortisol",
  "ayurveda-energy": "Energy",
  "ayurveda-exercise": "Exercise",
  "ayurveda-for-ibs": "Gut",
  "ayurveda-gut-health": "Gut",
  "ayurveda-hormonal-balance": "Women",
  "ayurveda-hormones-women": "Hormones",
  "ayurveda-ice-water": "Water",
  "ayurveda-meat-fish": "Diet",
  "ayurveda-sex": "Sex",
  "ayurvedic-herbs-guide": "Herbs",
  "ayurvedic-morning-routine": "Morning",
  "ayurvedic-skin-guide": "Skin",
  "ayurvedic-sleep-hygiene": "Sleep",
  "ayurvedic-tea-guide": "Tea",
  "ayurvedic-weight-loss": "Weight",
  "best-ayurvedic-tea-anxiety": "Anxiety",
  "best-morning-routine-for-energy": "Energy",
  "brain-fog-causes": "Fog",
  "high-cortisol-symptoms": "Cortisol",
  "how-to-calm-your-nervous-system": "Calm",
  "why-you-feel-tired-all-the-time": "Tired",
  "best-ayurvedic-tea-digestion": "Tea",
  "best-ayurvedic-tea-sleep": "Sleep",
  "best-herbs-for-anxiety": "Anxiety",
  "best-spices-for-digestion": "Digestion",
  "best-tea-for-bloating": "Bloating",
  "best-tea-for-digestion": "Tea",
  "best-tea-for-kapha": "Kapha",
  "best-tea-for-pitta": "Pitta",
  "best-tea-for-sleep": "Sleep",
  "best-tea-for-stress": "Tea",
  "best-tea-for-vata": "Vata",
  "brahmi-benefits": "Benefits",
  "chronic-pain-management": "Healing",
  "dopamine-detox-vs-ayurveda": "Ayurveda",
  "eating-for-your-dosha": "Dosha",
  "healing-after-chronic-stress": "Healing",
  "how-to-improve-digestion-naturally": "Digestion",
  "modern-wellness-rest": "Rest",
  "nervous-system-regulation-ayurveda": "Safe",
  "post-vacation-fatigue": "Vacation",
  "quiet-health-habits": "Quiet",
  "i-cant-lose-weight": "Weight",
  "i-have-no-energy": "Energy",
  "im-burned-out": "Burnout",
  "kapha-diet-plan": "Kapha",
  "kapha-dosha-guide": "Kapha",
  "kapha-foods-to-avoid": "Kapha",
  "kapha-morning-routine": "Morning",
  "leaky-gut-ayurveda": "Gut",
  "mens-guide-to-ashwagandha": "Men",
  "mens-sleep-guide-ayurveda": "Sleep",
  "nervous-system-burnout": "Burnout",
  "perimenopause-ayurveda": "Aging",
  "pitta-diet-plan": "Pitta",
  "pitta-dosha-guide": "Pitta",
  "pitta-foods-to-avoid": "Pitta",
  "pitta-morning-routine": "Morning",
  "retreat-day-1": "Day",
  "retreat-day-2": "Day",
  "retreat-day-3": "Day",
  "retreat-day-4": "Day",
  "retreat-day-5": "Day",
  "retreat-day-6": "Day",
  "signs-of-high-cortisol": "Cortisol",
  "stress-hair-loss-ayurveda": "Hair",
  "triphala-benefits": "Herbs",
  "vata-anxiety-guide": "Anxiety",
  "vata-diet-plan": "Vata",
  "vata-dosha-guide": "Vata",
  "vata-foods-to-avoid": "Vata",
  "vata-morning-routine": "Morning",
  "why-am-i-always-bloated": "Bloating",
  "why-am-i-always-tired": "Tired",
  "why-men-burn-out": "Vata",
  "why-im-building-doshaflow": "Safety",
}

