export interface Post {
  slug: string
  category: "journal" | "article"
  title: string
  date: string
  excerpt: string
  content: string
  seoTitle?: string
  seoDescription?: string
}

export const posts: Post[] = [
  {
    slug: "retreat-day-3",
    category: "journal",
    title: "Day 3: My Body Is Detoxing, My Mood Is a Ping Pong Ball, and I Hit 15,000 Steps",
    date: "May 27, 2026",
    excerpt: "First good night of sleep. Eight hours. My resting heart rate was 74. And then my digestive system staged a full revolt.",
    seoTitle: "What Really Happens at an Ayurvedic Retreat: Day 3 — Shirodhara, Detox & Mood Swings",
    seoDescription: "An honest first-person account of day 3 at an Ayurvedic retreat in India — Shirodhara treatment, detox side effects, mood swings, and what nobody warns you about before you go.",
    content: ``,
  },
  {
    slug: "retreat-day-4",
    category: "journal",
    title: "Retreat Journal Day 4: What a Vata Type Gets Wrong About Exercise",
    date: "May 28, 2026",
    excerpt: "Day 4 at an Ayurvedic retreat in Kerala: the doctor tells me to stop moving, shirodhara finally works, and I reckon with how much I've been avoiding the whole point of being here.",
    seoTitle: "Retreat Journal Day 4: What a Vata Type Gets Wrong About Exercise",
    seoDescription: "Day 4 at an Ayurvedic retreat in Kerala: the doctor tells me to stop moving, shirodhara finally works, and I reckon with how much I've been avoiding the whole point of being here.",
    content: ``,
  },
  {
    slug: "ayurveda-burnout",
    category: "article",
    title: "Burnout Through an Ayurvedic Lens: What's Actually Happening and How to Recover",
    date: "May 28, 2026",
    excerpt: "Ayurveda explains burnout as a depletion of ojas — vital essence — with specific patterns for Vata, Pitta, and Kapha types. Here's what the recovery actually looks like.",
    seoTitle: "Burnout Through an Ayurvedic Lens: What's Actually Happening and How to Recover",
    seoDescription: "Ayurveda explains burnout as a depletion of ojas — vital essence — with specific patterns for Vata, Pitta, and Kapha types. Here's what the recovery actually looks like.",
    content: ``,
  },
  {
    slug: "ayurveda-30-days",
    category: "article",
    title: "I Followed an Ayurvedic Routine for 30 Days: Here's What Actually Changed",
    date: "May 25, 2026",
    excerpt: "What happens when you consistently follow an Ayurvedic daily routine for 30 days? Digestion, sleep, anxiety, skin — an honest account of what changed and what didn't.",
    seoTitle: "I Followed an Ayurvedic Routine for 30 Days: Here's What Actually Changed",
    seoDescription: "What happens when you consistently follow an Ayurvedic daily routine for 30 days? Digestion, sleep, anxiety, skin — an honest account of what changed and what didn't.",
    content: ``,
  },
  {
    slug: "ayurveda-no-time",
    category: "article",
    title: "Ayurveda for Busy People: 7 Practices That Take Under 30 Minutes a Day",
    date: "May 23, 2026",
    excerpt: "You don't need to overhaul your life to benefit from Ayurveda. Here are the 7 highest-leverage Ayurvedic practices for people who are actually busy — and what they do.",
    seoTitle: "Ayurveda for Busy People: 7 Practices That Take Under 30 Minutes a Day",
    seoDescription: "You don't need to overhaul your life to benefit from Ayurveda. Here are the 7 highest-leverage Ayurvedic practices for people who are actually busy — and what they do.",
    content: ``,
  },
  {
    slug: "ayurveda-pms",
    category: "article",
    title: "The Ayurvedic Approach to PMS: Three Patterns and What to Do About Each",
    date: "May 22, 2026",
    excerpt: "Ayurveda identifies three distinct PMS patterns — Vata, Pitta, and Kapha — each with different causes and different remedies. Here's how to identify yours and what actually helps.",
    seoTitle: "The Ayurvedic Approach to PMS: Three Patterns and What to Do About Each",
    seoDescription: "Ayurveda identifies three distinct PMS patterns — Vata, Pitta, and Kapha — each with different causes and different remedies. Here's how to identify yours and what actually helps.",
    content: ``,
  },
  {
    slug: "eating-for-your-dosha",
    category: "article",
    title: "Eating for Your Dosha: The Ayurvedic Diet Guide for Vata, Pitta, and Kapha",
    date: "May 19, 2026",
    excerpt: "Ayurvedic eating isn't a diet — it's a framework for matching food to your constitution. Learn what to eat for Vata, Pitta, and Kapha doshas with practical, specific guidance.",
    seoTitle: "Eating for Your Dosha: The Ayurvedic Diet Guide for Vata, Pitta, and Kapha",
    seoDescription: "Ayurvedic eating isn't a diet — it's a framework for matching food to your constitution. Learn what to eat for Vata, Pitta, and Kapha doshas with practical, specific guidance.",
    content: ``,
  },
  {
    slug: "ayurveda-hormonal-balance",
    category: "article",
    title: "Ayurveda for Hormonal Balance: What I Wish I'd Known Sooner",
    date: "May 21, 2026",
    excerpt: "I spent the better part of my twenties being told my hormones were 'normal.' Ayurveda lives in the gray zone between thriving and diagnosable — and it reframed everything I understood about hormones.",
    seoTitle: "Ayurveda for Hormonal Balance: What the Ancient System Gets Right",
    seoDescription: "Ayurveda offers a sophisticated framework for women's hormonal health — from dosha-specific patterns to herbs like Shatavari and Ashwagandha. Here's what I've learned.",
    content: ``,
  },
  {
    slug: "ayurveda-meat-fish",
    category: "article",
    title: "Can You Eat Meat and Fish on an Ayurvedic Diet? The Answer Is More Complicated Than You Think.",
    date: "May 26, 2026",
    excerpt: "The vegetarian Ayurveda most people know is a modern Western construction. The classical texts call meat nourishing and even medicinal — here's the real, dosha-specific picture.",
    seoTitle: "Can You Eat Meat and Fish on an Ayurvedic Diet? The Answer Is More Complicated Than You Think.",
    seoDescription: "The vegetarian Ayurveda most people know is a modern Western construction. The classical texts call meat nourishing and even medicinal — here's the real, dosha-specific picture.",
    content: ``,
  },
  {
    slug: "ayurveda-alcohol",
    category: "article",
    title: "Ayurveda Has Its Own Version of Alcohol. Here's What the Texts Actually Say.",
    date: "May 27, 2026",
    excerpt: "Before you assume Ayurveda tells you to stop drinking, know this: the classical texts contain entire chapters on fermented drinks. Here's the nuanced, dosha-specific picture.",
    seoTitle: "Ayurveda Has Its Own Version of Alcohol. Here's What the Texts Actually Say.",
    seoDescription: "Before you assume Ayurveda tells you to stop drinking, know this: the classical texts contain entire chapters on fermented drinks. Here's the nuanced, dosha-specific picture.",
    content: ``,
  },
  {
    slug: "ayurveda-ice-water",
    category: "article",
    title: "Why Ayurveda Says You Should Never Drink Ice Water (And Why It's Probably Right)",
    date: "May 28, 2026",
    excerpt: "Warm water, never ice. It's one of the most consistent recommendations in Ayurveda — and once you understand agni, digestive fire, it's hard to go back.",
    seoTitle: "Why Ayurveda Says You Should Never Drink Ice Water (And Why It's Probably Right)",
    seoDescription: "Warm water, never ice. It's one of the most consistent recommendations in Ayurveda — and once you understand agni, digestive fire, it's hard to go back.",
    content: ``,
  },
  {
    slug: "ayurveda-exercise",
    category: "article",
    title: "Why Working Out the Same Way Every Day Is Making You Worse (According to Ayurveda)",
    date: "May 29, 2026",
    excerpt: "Ayurveda treats exercise as constitution-specific, not universal. Here's what each dosha actually needs, when to train, and why recovery matters as much as exertion.",
    seoTitle: "Why Working Out the Same Way Every Day Is Making You Worse (According to Ayurveda)",
    seoDescription: "Ayurveda treats exercise as constitution-specific, not universal. Here's what each dosha actually needs, when to train, and why recovery matters as much as exertion.",
    content: ``,
  },
  {
    slug: "ayurveda-sex",
    category: "article",
    title: "The Branch of Ayurveda Nobody Talks About: Sex, Vitality, and Vajikarana",
    date: "May 30, 2026",
    excerpt: "Vajikarana is the eighth classical branch of Ayurveda, dedicated to sexual health and vitality. Here's what the texts actually say — about Ojas, doshas, and the herbs.",
    seoTitle: "The Branch of Ayurveda Nobody Talks About: Sex, Vitality, and Vajikarana",
    seoDescription: "Vajikarana is the eighth classical branch of Ayurveda, dedicated to sexual health and vitality. Here's what the texts actually say — about Ojas, doshas, and the herbs.",
    content: ``,
  },
  {
    slug: "ayurveda-aging",
    category: "article",
    title: "Why Your 40s Are Supposed to Feel Different: The Ayurvedic Map of Life",
    date: "May 31, 2026",
    excerpt: "Ayurveda divides life into three dosha-governed stages. Understanding the Pitta-to-Vata transition explains why your 40s feel different — and how to work with it.",
    seoTitle: "Why Your 40s Are Supposed to Feel Different: The Ayurvedic Map of Life",
    seoDescription: "Ayurveda divides life into three dosha-governed stages. Understanding the Pitta-to-Vata transition explains why your 40s feel different — and how to work with it.",
    content: ``,
  },
  {
    slug: "ayurveda-coffee",
    category: "article",
    title: "The Ayurvedic Take on Coffee",
    date: "May 20, 2026",
    excerpt: "The question I get asked most often when I tell people I've been at an Ayurvedic retreat is: 'Can you still have coffee?' The answer is nuanced, which is very Ayurvedic of it.",
    seoTitle: "The Ayurvedic Take on Coffee: Should You Drink It or Give It Up?",
    seoDescription: "Ayurveda has a nuanced take on coffee — it depends on your dosha. Here's how coffee affects Vata, Pitta, and Kapha types, and how to make it work better for your constitution.",
    content: ``,
  },
  {
    slug: "ayurveda-cold-smoothies",
    category: "article",
    title: "Why Ayurveda Doesn't Believe in Cold Smoothies (And What to Eat Instead)",
    date: "May 18, 2026",
    excerpt: "I drank a green smoothie every morning for three years. Then I sat with an Ayurvedic practitioner in Kerala and she said: 'That explains the bloating.'",
    seoTitle: "Why Ayurveda Doesn't Recommend Cold Smoothies (And What to Eat Instead)",
    seoDescription: "Ayurveda says cold smoothies suppress digestive fire — and the science of agni explains why. Here's what to eat for breakfast instead, according to your dosha.",
    content: ``,
  },
  {
    slug: "kapha-dosha-guide",
    category: "article",
    title: "Kapha Dosha: Why You Feel Stuck, Sluggish, and What Actually Helps",
    date: "May 17, 2026",
    excerpt: "Kapha is the dosha nobody talks about. Here's what I've learned: Kapha imbalance isn't a character flaw. It's an energetic pattern with specific causes and solutions.",
    seoTitle: "Kapha Dosha: Why You Feel Sluggish and What Actually Helps",
    seoDescription: "Kapha dosha governs stability, structure, and endurance. Learn the signs of Kapha imbalance — sluggishness, weight gain, low motivation — and how to get your energy moving again.",
    content: ``,
  },
  {
    slug: "pitta-dosha-guide",
    category: "article",
    title: "Pitta Dosha: The High-Achiever's Guide to Cooling Down",
    date: "May 16, 2026",
    excerpt: "The first time someone described Pitta to me, I laughed. Not because it was wrong. Because it was so accurate it was slightly embarrassing.",
    seoTitle: "Pitta Dosha: Signs of Imbalance and How to Cool Down",
    seoDescription: "Pitta dosha governs fire, digestion, and ambition. Learn the signs of Pitta imbalance — inflammation, irritability, burnout — and exactly how to bring it back into balance.",
    content: ``,
  },
  {
    slug: "vata-dosha-guide",
    category: "article",
    title: "Vata Dosha: Signs You're Out of Balance and What To Do About It",
    date: "May 15, 2026",
    excerpt: "I used to think anxiety was just my personality. Then I got my dosha assessment and the practitioner said: 'Classic Vata imbalance.' Everything had a name — and a remedy.",
    seoTitle: "Vata Dosha: Signs You're Out of Balance and How to Fix It",
    seoDescription: "Vata dosha governs movement, creativity, and the nervous system. Learn the signs of Vata imbalance — anxiety, dry skin, insomnia — and exactly how to bring it back into balance.",
    content: ``,
  },
  {
    slug: "ayurvedic-herbs-guide",
    category: "article",
    title: "The Ayurvedic Herb Guide: What's Actually in These Formulas and Why",
    date: "May 28, 2026",
    excerpt: "I'm sitting in a pharmacy that's been operating for over 200 years. Here's what I learned about the herbs that show up in every Ayurvedic formula — and why they work.",
    seoTitle: "Ayurvedic Herbs: A Practical Guide to Ashwagandha, Triphala, Brahmi & More",
    seoDescription: "A practical guide to the most important Ayurvedic herbs — what they do, the evidence behind them, and how to match them to your dosha type.",
    content: ``,
  },
]

export function getPostBySlug(slug: string): Post | undefined {
  return posts.find((post) => post.slug === slug)
}

export function getAllPosts(): Post[] {
  return posts
}
