export interface Post {
  slug: string
  category: "journal" | "article"
  title: string
  date: string
  excerpt: string
  content: string
  seoTitle?: string
  seoDescription?: string
}

export const posts: Post[] = [
  {
    slug: "ayurvedic-skin-guide",
    category: "article",
    title: "The Ayurvedic Skin Guide: Why Your Skin Reflects What Is Happening Inside",
    date: "June 15, 2026",
    excerpt: "Ayurveda treats skin conditions from the inside — through the gut, liver, and doshas. The complete guide to Ayurvedic skincare by skin type, herbs, diet, and external practices.",
    seoTitle: "The Ayurvedic Skin Guide: Why Your Skin Reflects What Is Happening Inside",
    seoDescription: "Ayurveda treats skin conditions from the inside — through the gut, liver, and doshas. The complete guide to Ayurvedic skincare by skin type, herbs, diet, and external practices.",
    content: ``,
  },
  {
    slug: "kapha-foods-to-avoid",
    category: "article",
    title: "Kapha Foods to Avoid: Why You Feel Heavy, Tired, and Stuck",
    date: "June 8, 2026",
    excerpt: "The complete list of foods that aggravate Kapha dosha — dairy, wheat, sweets, cold food, and large portions. Why each one makes Kapha fatigue and weight gain worse.",
    seoTitle: "Kapha Foods to Avoid: Why You Feel Heavy, Tired, and Stuck",
    seoDescription: "The complete list of foods that aggravate Kapha dosha — dairy, wheat, sweets, cold food, and large portions. Why each one makes Kapha fatigue and weight gain worse.",
    content: ``,
  },
  {
    slug: "vata-foods-to-avoid",
    category: "article",
    title: "Vata Foods to Avoid: What Is Making Your Anxiety and Digestion Worse",
    date: "June 7, 2026",
    excerpt: "The complete list of foods that aggravate Vata dosha — cold food, dry snacks, caffeine, carbonated drinks, and irregular eating. Why each one makes Vata symptoms worse.",
    seoTitle: "Vata Foods to Avoid: What Is Making Your Anxiety and Digestion Worse",
    seoDescription: "The complete list of foods that aggravate Vata dosha — cold food, dry snacks, caffeine, carbonated drinks, and irregular eating. Why each one makes Vata symptoms worse.",
    content: ``,
  },
  {
    slug: "ayurveda-alcohol-recovery",
    category: "article",
    title: "Ayurveda and Alcohol Recovery: What the System Actually Offers",
    date: "June 6, 2026",
    excerpt: "Ayurveda offers specific herbs and practices for alcohol recovery — ashwagandha, brahmi, triphala, and a nervous system reset protocol. An honest account of what it does and does not do.",
    seoTitle: "Ayurveda and Alcohol Recovery: What the System Actually Offers",
    seoDescription: "Ayurveda offers specific herbs and practices for alcohol recovery — ashwagandha, brahmi, triphala, and a nervous system reset protocol. An honest account of what it does and does not do.",
    content: ``,
  },
  {
    slug: "why-am-i-always-tired",
    category: "article",
    title: "Why Am I Always Tired? The Ayurvedic Explanation by Dosha Type",
    date: "June 5, 2026",
    excerpt: "Persistent fatigue has three different causes in Ayurveda — Vata depletion, Pitta inflammation, and Kapha sluggishness. Identifying yours changes everything about what to do.",
    seoTitle: "Why Am I Always Tired? The Ayurvedic Explanation by Dosha Type",
    seoDescription: "Persistent fatigue has three different causes in Ayurveda — Vata depletion, Pitta inflammation, and Kapha sluggishness. Identifying yours changes everything about what to do.",
    content: ``,
  },
  {
    slug: "nervous-system-burnout",
    category: "article",
    title: "Signs of Nervous System Burnout — And the Ayurvedic Path Back",
    date: "June 4, 2026",
    excerpt: "Nervous system burnout is not ordinary tiredness. Here are the specific signs, what causes it in Ayurvedic terms, and the recovery protocol that actually works.",
    seoTitle: "Signs of Nervous System Burnout — And the Ayurvedic Path Back",
    seoDescription: "Nervous system burnout is not ordinary tiredness. Here are the specific signs, what causes it in Ayurvedic terms, and the recovery protocol that actually works.",
    content: ``,
  },
  {
    slug: "kapha-morning-routine",
    category: "article",
    title: "Kapha Morning Routine: How to Actually Wake Up",
    date: "June 3, 2026",
    excerpt: "The Ayurvedic morning routine for Kapha — why waking before 6am matters, why breakfast should be skipped, and why vigorous exercise before eating is non-negotiable for Kapha types.",
    seoTitle: "Kapha Morning Routine: How to Actually Wake Up",
    seoDescription: "The Ayurvedic morning routine for Kapha — why waking before 6am matters, why breakfast should be skipped, and why vigorous exercise before eating is non-negotiable for Kapha types.",
    content: ``,
  },
  {
    slug: "pitta-anger-sleep",
    category: "article",
    title: "Pitta and Anger: Why You Are Irritable, Inflamed, and Not Sleeping",
    date: "June 2, 2026",
    excerpt: "Pitta imbalance causes anger, skin inflammation, acid reflux, and the 10pm-2am sleep disruption pattern. Here is what is happening and what actually helps.",
    seoTitle: "Pitta and Anger: Why You Are Irritable, Inflamed, and Not Sleeping",
    seoDescription: "Pitta imbalance causes anger, skin inflammation, acid reflux, and the 10pm-2am sleep disruption pattern. Here is what is happening and what actually helps.",
    content: ``,
  },
  {
    slug: "signs-of-vata-imbalance",
    category: "article",
    title: "Signs of Vata Imbalance: Is Your Nervous System Running on Empty?",
    date: "June 1, 2026",
    excerpt: "Dry skin, constipation, racing thoughts, anxiety without cause — the complete guide to Vata imbalance symptoms, what causes them, and how to bring Vata back into balance.",
    seoTitle: "Signs of Vata Imbalance: Is Your Nervous System Running on Empty?",
    seoDescription: "Dry skin, constipation, racing thoughts, anxiety without cause — the complete guide to Vata imbalance symptoms, what causes them, and how to bring Vata back into balance.",
    content: ``,
  },
  {
    slug: "ayurvedic-weight-loss",
    category: "article",
    title: "Ayurvedic Weight Loss Guide: Why Diets Do Not Work for Your Dosha (And What Does)",
    date: "May 30, 2026",
    excerpt: "Ayurveda explains weight gain by dosha — Vata, Pitta, and Kapha each gain weight for different reasons and need different approaches. The complete Ayurvedic weight loss guide.",
    seoTitle: "Ayurvedic Weight Loss Guide: Why Diets Do Not Work for Your Dosha (And What Does)",
    seoDescription: "Ayurveda explains weight gain by dosha — Vata, Pitta, and Kapha each gain weight for different reasons and need different approaches. The complete Ayurvedic weight loss guide.",
    content: ``,
  },
  {
    slug: "best-ayurvedic-tea-digestion",
    category: "article",
    title: "Best Ayurvedic Tea for Digestion: What to Drink Before, During, and After Meals",
    date: "May 29, 2026",
    excerpt: "The best Ayurvedic teas for digestion — ginger, CCF tea, fennel, triphala. What to drink before and after meals to fix bloating, gas, constipation, and sluggish digestion.",
    seoTitle: "Best Ayurvedic Tea for Digestion: What to Drink Before, During, and After Meals",
    seoDescription: "The best Ayurvedic teas for digestion — ginger, CCF tea, fennel, triphala. What to drink before and after meals to fix bloating, gas, constipation, and sluggish digestion.",
    content: ``,
  },
  {
    slug: "best-ayurvedic-tea-sleep",
    category: "article",
    title: "Best Ayurvedic Tea for Sleep: The Herbs That Actually Work",
    date: "May 28, 2026",
    excerpt: "The best Ayurvedic teas for sleep — jatamansi, ashwagandha, brahmi, valerian. What the herbs do, when to take them, and the warm milk ritual that outperforms most sleep teas.",
    seoTitle: "Best Ayurvedic Tea for Sleep: The Herbs That Actually Work",
    seoDescription: "The best Ayurvedic teas for sleep — jatamansi, ashwagandha, brahmi, valerian. What the herbs do, when to take them, and the warm milk ritual that outperforms most sleep teas.",
    content: ``,
  },
  {
    slug: "best-ayurvedic-tea-anxiety",
    category: "article",
    title: "Best Ayurvedic Tea for Anxiety: What to Drink, When, and Why",
    date: "May 27, 2026",
    excerpt: "The best Ayurvedic teas for anxiety by dosha type — ashwagandha, brahmi, jatamansi, and tulsi with practical blends and timing for Vata, Pitta, and Kapha anxiety.",
    seoTitle: "Best Ayurvedic Tea for Anxiety: What to Drink, When, and Why",
    seoDescription: "The best Ayurvedic teas for anxiety by dosha type — ashwagandha, brahmi, jatamansi, and tulsi with practical blends and timing for Vata, Pitta, and Kapha anxiety.",
    content: ``,
  },
  {
    slug: "kapha-diet-plan",
    category: "article",
    title: "Kapha Diet Plan: How to Eat for Energy When Your Body Wants to Do Nothing",
    date: "May 26, 2026",
    excerpt: "The complete Kapha diet plan — best foods to stimulate Kapha metabolism, what to avoid, and a practical daily template including the most common Kapha mistakes.",
    seoTitle: "Kapha Diet Plan: How to Eat for Energy When Your Body Wants to Do Nothing",
    seoDescription: "The complete Kapha diet plan — best foods to stimulate Kapha metabolism, what to avoid, and a practical daily template including the most common Kapha mistakes.",
    content: ``,
  },
  {
    slug: "pitta-diet-plan",
    category: "article",
    title: "Pitta Diet Plan: How to Cool the Fire Without Losing the Edge",
    date: "May 25, 2026",
    excerpt: "The complete Pitta diet plan — best foods to cool Pitta, what to avoid, and a practical daily template including the most common Pitta dietary mistakes.",
    seoTitle: "Pitta Diet Plan: How to Cool the Fire Without Losing the Edge",
    seoDescription: "The complete Pitta diet plan — best foods to cool Pitta, what to avoid, and a practical daily template including the most common Pitta dietary mistakes.",
    content: ``,
  },
  {
    slug: "vata-diet-plan",
    category: "article",
    title: "Vata Diet Plan: What to Eat, What to Avoid, and How to Fix Your Digestion",
    date: "May 24, 2026",
    excerpt: "The complete Vata diet plan — best foods for Vata dosha, what to avoid, and a practical daily template including the most common Vata dietary mistakes.",
    seoTitle: "Vata Diet Plan: What to Eat, What to Avoid, and How to Fix Your Digestion",
    seoDescription: "The complete Vata diet plan — best foods for Vata dosha, what to avoid, and a practical daily template including the most common Vata dietary mistakes.",
    content: ``,
  },
  {
    slug: "retreat-day-6",
    category: "journal",
    title: "Day 6: The Enema, the Standoff, and the Temple Behind the Bodega.",
    date: "May 30, 2026",
    excerpt: "1.5 hours of sleep, treatment refusal, a temple behind a bodega, and the anxiety of thinking about leaving. Day 6 at the Ayurvedic retreat in Kerala.",
    seoTitle: "Day 6: The Enema, the Standoff, and the Temple Behind the Bodega.",
    seoDescription: "An honest first-person account of day 6 at an Ayurvedic retreat in India — treatment refusal, spiritual wandering, and the weight of self-awareness.",
    content: ``,
  },
  {
    slug: "retreat-day-5",
    category: "journal",
    title: "Day 5: I Watched the NBA Finals at 6am, Got Poured Buttermilk on My Head, and Still Can't Turn My Brain Off",
    date: "May 30, 2026",
    excerpt: "3.5 hours of sleep, back pain gone, buttermilk treatment, and the unsettling realization that I need to lean in harder. Day 5 at the Ayurvedic retreat in Kerala.",
    seoTitle: "Day 5: I Watched the NBA Finals at 6am, Got Poured Buttermilk on My Head, and Still Can't Turn My Brain Off",
    seoDescription: "An honest first-person account of day 5 at an Ayurvedic retreat in India — yoga breakthroughs, portion control recalibration, sound bath paradoxes, and the ongoing battle between the mind and the body.",
    content: ``,
  },
  {
    slug: "signs-of-high-cortisol",
    category: "article",
    title: "Signs of High Cortisol — And What Ayurveda Does About It",
    date: "May 30, 2026",
    excerpt: "Belly fat, waking at 3am, afternoon crashes — these are signs of elevated cortisol. Here is what Ayurveda identifies as the cause and the fix.",
    seoTitle: "Signs of High Cortisol — And What Ayurveda Does About It",
    seoDescription: "Belly fat, waking at 3am, afternoon crashes — these are signs of elevated cortisol. Here is what Ayurveda identifies as the cause and the fix.",
    content: ``,
  },
  {
    slug: "best-herbs-for-anxiety",
    category: "article",
    title: "Best Ayurvedic Herbs for Anxiety: What Actually Works and Why",
    date: "May 29, 2026",
    excerpt: "Ayurveda has specific herbs for anxiety — not sedatives, but nervines that nourish the stressed nervous system. Here is what works and how to use it correctly.",
    seoTitle: "Best Ayurvedic Herbs for Anxiety: What Actually Works and Why",
    seoDescription: "Ayurveda has specific herbs for anxiety — not sedatives, but nervines that nourish the stressed nervous system. Here is what works and how to use it correctly.",
    content: ``,
  },
  {
    slug: "ayurvedic-morning-routine",
    category: "article",
    title: "Ayurvedic Morning Routine: The Complete Step-by-Step Guide",
    date: "May 28, 2026",
    excerpt: "The complete Ayurvedic morning routine — what to do, in order, and why. Includes the realistic 15-minute version for people with real lives.",
    seoTitle: "Ayurvedic Morning Routine: The Complete Step-by-Step Guide",
    seoDescription: "The complete Ayurvedic morning routine — what to do, in order, and why. Includes the realistic 15-minute version for people with real lives.",
    content: ``,
  },
  {
    slug: "ashwagandha-benefits",
    category: "article",
    title: "Ashwagandha Benefits: What the Research Actually Says (And What Ayurveda Has Known for 3,000 Years)",
    date: "May 27, 2026",
    excerpt: "Ashwagandha is the most researched Ayurvedic herb in Western science. Here is what the clinical trials actually show — and how to use it correctly.",
    seoTitle: "Ashwagandha Benefits: What the Research Actually Says (And What Ayurveda Has Known for 3,000 Years)",
    seoDescription: "Ashwagandha is the most researched Ayurvedic herb in Western science. Here is what the clinical trials actually show — and how to use it correctly.",
    content: ``,
  },
  {
    slug: "why-am-i-always-bloated",
    category: "article",
    title: "Why Am I Always Bloated? The Ayurvedic Explanation (And What to Do About It)",
    date: "May 26, 2026",
    excerpt: "Chronic bloating is not random. Ayurveda explains it as weak digestive fire and Vata imbalance — with specific fixes that go beyond cutting food groups.",
    seoTitle: "Why Am I Always Bloated? The Ayurvedic Explanation (And What to Do About It)",
    seoDescription: "Chronic bloating is not random. Ayurveda explains it as weak digestive fire and Vata imbalance — with specific fixes that go beyond cutting food groups.",
    content: ``,
  },
  {
    slug: "ayurvedic-tea-guide",
    category: "article",
    title: "Ayurvedic Tea Guide: Best Teas for Vata, Pitta, and Kapha Dosha",
    date: "May 25, 2026",
    excerpt: "The complete guide to Ayurvedic tea by dosha — which herbs Vata, Pitta, and Kapha types actually need, and how to use herbal tea as a daily health practice.",
    seoTitle: "Ayurvedic Tea Guide: Best Teas for Vata, Pitta, and Kapha Dosha",
    seoDescription: "The complete guide to Ayurvedic tea by dosha — which herbs Vata, Pitta, and Kapha types actually need, and how to use herbal tea as a daily health practice.",
    content: ``,
  },
  {
    slug: "retreat-day-3",
    category: "journal",
    title: "Day 3: My Body Is Detoxing, My Mood Is a Ping Pong Ball, and I Hit 15,000 Steps",
    date: "May 27, 2026",
    excerpt: "First good night of sleep. Eight hours. My resting heart rate was 74. And then my digestive system staged a full revolt.",
    seoTitle: "What Really Happens at an Ayurvedic Retreat: Day 3 — Shirodhara, Detox & Mood Swings",
    seoDescription: "An honest first-person account of day 3 at an Ayurvedic retreat in India — Shirodhara treatment, detox side effects, mood swings, and what nobody warns you about before you go.",
    content: ``,
  },
  {
    slug: "retreat-day-4",
    category: "journal",
    title: "Retreat Journal Day 4: What a Vata Type Gets Wrong About Exercise",
    date: "May 28, 2026",
    excerpt: "Day 4 at an Ayurvedic retreat in Kerala: the doctor tells me to stop moving, shirodhara finally works, and I reckon with how much I've been avoiding the whole point of being here.",
    seoTitle: "Retreat Journal Day 4: What a Vata Type Gets Wrong About Exercise",
    seoDescription: "Day 4 at an Ayurvedic retreat in Kerala: the doctor tells me to stop moving, shirodhara finally works, and I reckon with how much I've been avoiding the whole point of being here.",
    content: ``,
  },
  {
    slug: "ayurveda-burnout",
    category: "article",
    title: "Burnout Symptoms and Recovery: The Ayurvedic Explanation",
    date: "May 28, 2026",
    excerpt: "Ayurveda explains burnout as a depletion of ojas — vital essence — with specific patterns for Vata, Pitta, and Kapha types. Here's what the recovery actually looks like.",
    seoTitle: "Burnout Through an Ayurvedic Lens: What's Actually Happening and How to Recover",
    seoDescription: "Ayurveda explains burnout as a depletion of ojas — vital essence — with specific patterns for Vata, Pitta, and Kapha types. Here's what the recovery actually looks like.",
    content: ``,
  },
  {
    slug: "ayurveda-30-days",
    category: "article",
    title: "I Followed an Ayurvedic Routine for 30 Days: Here's What Actually Changed",
    date: "May 25, 2026",
    excerpt: "What happens when you consistently follow an Ayurvedic daily routine for 30 days? Digestion, sleep, anxiety, skin — an honest account of what changed and what didn't.",
    seoTitle: "I Followed an Ayurvedic Routine for 30 Days: Here's What Actually Changed",
    seoDescription: "What happens when you consistently follow an Ayurvedic daily routine for 30 days? Digestion, sleep, anxiety, skin — an honest account of what changed and what didn't.",
    content: ``,
  },
  {
    slug: "ayurveda-no-time",
    category: "article",
    title: "Simple Ayurvedic Daily Routine for Busy People (Under 30 Minutes)",
    date: "May 23, 2026",
    excerpt: "You don't need to overhaul your life to benefit from Ayurveda. Here are the 7 highest-leverage Ayurvedic practices for people who are actually busy — and what they do.",
    seoTitle: "Ayurveda for Busy People: 7 Practices That Take Under 30 Minutes a Day",
    seoDescription: "You don't need to overhaul your life to benefit from Ayurveda. Here are the 7 highest-leverage Ayurvedic practices for people who are actually busy — and what they do.",
    content: ``,
  },
  {
    slug: "ayurveda-pms",
    category: "article",
    title: "Natural PMS Relief: The Ayurvedic Approach by Dosha Type",
    date: "May 22, 2026",
    excerpt: "Ayurveda identifies three distinct PMS patterns — Vata, Pitta, and Kapha — each with different causes and different remedies. Here's how to identify yours and what actually helps.",
    seoTitle: "The Ayurvedic Approach to PMS: Three Patterns and What to Do About Each",
    seoDescription: "Ayurveda identifies three distinct PMS patterns — Vata, Pitta, and Kapha — each with different causes and different remedies. Here's how to identify yours and what actually helps.",
    content: ``,
  },
  {
    slug: "eating-for-your-dosha",
    category: "article",
    title: "Eating for Your Dosha: The Ayurvedic Diet Guide for Vata, Pitta, and Kapha",
    date: "May 19, 2026",
    excerpt: "Ayurvedic eating isn't a diet — it's a framework for matching food to your constitution. Learn what to eat for Vata, Pitta, and Kapha doshas with practical, specific guidance.",
    seoTitle: "Eating for Your Dosha: The Ayurvedic Diet Guide for Vata, Pitta, and Kapha",
    seoDescription: "Ayurvedic eating isn't a diet — it's a framework for matching food to your constitution. Learn what to eat for Vata, Pitta, and Kapha doshas with practical, specific guidance.",
    content: ``,
  },
  {
    slug: "ayurveda-hormonal-balance",
    category: "article",
    title: "Hormonal Imbalance Symptoms and Natural Remedies — Ayurvedic Guide",
    date: "May 21, 2026",
    excerpt: "I spent the better part of my twenties being told my hormones were 'normal.' Ayurveda lives in the gray zone between thriving and diagnosable — and it reframed everything I understood about hormones.",
    seoTitle: "Ayurveda for Hormonal Balance: What the Ancient System Gets Right",
    seoDescription: "Ayurveda offers a sophisticated framework for women's hormonal health — from dosha-specific patterns to herbs like Shatavari and Ashwagandha. Here's what I've learned.",
    content: ``,
  },
  {
    slug: "ayurveda-meat-fish",
    category: "article",
    title: "Can You Eat Meat on an Ayurvedic Diet? What the Classical Texts Say",
    date: "May 26, 2026",
    excerpt: "The vegetarian Ayurveda most people know is a modern Western construction. The classical texts call meat nourishing and even medicinal — here's the real, dosha-specific picture.",
    seoTitle: "Can You Eat Meat and Fish on an Ayurvedic Diet? The Answer Is More Complicated Than You Think.",
    seoDescription: "The vegetarian Ayurveda most people know is a modern Western construction. The classical texts call meat nourishing and even medicinal — here's the real, dosha-specific picture.",
    content: ``,
  },
  {
    slug: "ayurveda-alcohol",
    category: "article",
    title: "Alcohol and Ayurveda: What the Classical Texts Actually Say",
    date: "May 27, 2026",
    excerpt: "Before you assume Ayurveda tells you to stop drinking, know this: the classical texts contain entire chapters on fermented drinks. Here's the nuanced, dosha-specific picture.",
    seoTitle: "Ayurveda Has Its Own Version of Alcohol. Here's What the Texts Actually Say.",
    seoDescription: "Before you assume Ayurveda tells you to stop drinking, know this: the classical texts contain entire chapters on fermented drinks. Here's the nuanced, dosha-specific picture.",
    content: ``,
  },
  {
    slug: "ayurveda-ice-water",
    category: "article",
    title: "Why Cold Water Causes Bloating — The Ayurvedic Explanation",
    date: "May 28, 2026",
    excerpt: "Warm water, never ice. It's one of the most consistent recommendations in Ayurveda — and once you understand agni, digestive fire, it's hard to go back.",
    seoTitle: "Why Ayurveda Says You Should Never Drink Ice Water (And Why It's Probably Right)",
    seoDescription: "Warm water, never ice. It's one of the most consistent recommendations in Ayurveda — and once you understand agni, digestive fire, it's hard to go back.",
    content: ``,
  },
  {
    slug: "ayurveda-exercise",
    category: "article",
    title: "Why Working Out the Same Way Every Day Is Making You Worse (According to Ayurveda)",
    date: "May 29, 2026",
    excerpt: "Ayurveda treats exercise as constitution-specific, not universal. Here's what each dosha actually needs, when to train, and why recovery matters as much as exertion.",
    seoTitle: "Why Working Out the Same Way Every Day Is Making You Worse (According to Ayurveda)",
    seoDescription: "Ayurveda treats exercise as constitution-specific, not universal. Here's what each dosha actually needs, when to train, and why recovery matters as much as exertion.",
    content: ``,
  },
  {
    slug: "ayurveda-sex",
    category: "article",
    title: "Ayurvedic Guide to Vitality and Sexual Health: Vajikarana Explained",
    date: "May 30, 2026",
    excerpt: "Vajikarana is the eighth classical branch of Ayurveda, dedicated to sexual health and vitality. Here's what the texts actually say — about Ojas, doshas, and the herbs.",
    seoTitle: "The Branch of Ayurveda Nobody Talks About: Sex, Vitality, and Vajikarana",
    seoDescription: "Vajikarana is the eighth classical branch of Ayurveda, dedicated to sexual health and vitality. Here's what the texts actually say — about Ojas, doshas, and the herbs.",
    content: ``,
  },
  {
    slug: "ayurveda-aging",
    category: "article",
    title: "Why Your 40s Feel Different: The Ayurvedic Stages of Life Explained",
    date: "May 31, 2026",
    excerpt: "Ayurveda divides life into three dosha-governed stages. Understanding the Pitta-to-Vata transition explains why your 40s feel different — and how to work with it.",
    seoTitle: "Why Your 40s Are Supposed to Feel Different: The Ayurvedic Map of Life",
    seoDescription: "Ayurveda divides life into three dosha-governed stages. Understanding the Pitta-to-Vata transition explains why your 40s feel different — and how to work with it.",
    content: ``,
  },
  {
    slug: "ayurveda-coffee",
    category: "article",
    title: "Is Coffee Bad for You? The Ayurvedic Answer by Dosha",
    date: "May 20, 2026",
    excerpt: "The question I get asked most often when I tell people I've been at an Ayurvedic retreat is: 'Can you still have coffee?' The answer is nuanced, which is very Ayurvedic of it.",
    seoTitle: "The Ayurvedic Take on Coffee: Should You Drink It or Give It Up?",
    seoDescription: "Ayurveda has a nuanced take on coffee — it depends on your dosha. Here's how coffee affects Vata, Pitta, and Kapha types, and how to make it work better for your constitution.",
    content: ``,
  },
  {
    slug: "ayurveda-cold-smoothies",
    category: "article",
    title: "Are Cold Smoothies Bad for Digestion? What Ayurveda Says",
    date: "May 18, 2026",
    excerpt: "I drank a green smoothie every morning for three years. Then I sat with an Ayurvedic practitioner in Kerala and she said: 'That explains the bloating.'",
    seoTitle: "Why Ayurveda Doesn't Recommend Cold Smoothies (And What to Eat Instead)",
    seoDescription: "Ayurveda says cold smoothies suppress digestive fire — and the science of agni explains why. Here's what to eat for breakfast instead, according to your dosha.",
    content: ``,
  },
  {
    slug: "kapha-dosha-guide",
    category: "article",
    title: "Kapha Dosha: Why You Feel Stuck, Sluggish, and What Actually Helps",
    date: "May 17, 2026",
    excerpt: "Kapha is the dosha nobody talks about. Here's what I've learned: Kapha imbalance isn't a character flaw. It's an energetic pattern with specific causes and solutions.",
    seoTitle: "Kapha Dosha: Why You Feel Sluggish and What Actually Helps",
    seoDescription: "Kapha dosha governs stability, structure, and endurance. Learn the signs of Kapha imbalance — sluggishness, weight gain, low motivation — and how to get your energy moving again.",
    content: ``,
  },
  {
    slug: "pitta-dosha-guide",
    category: "article",
    title: "Pitta Dosha: The High-Achiever's Guide to Cooling Down",
    date: "May 16, 2026",
    excerpt: "The first time someone described Pitta to me, I laughed. Not because it was wrong. Because it was so accurate it was slightly embarrassing.",
    seoTitle: "Pitta Dosha: Signs of Imbalance and How to Cool Down",
    seoDescription: "Pitta dosha governs fire, digestion, and ambition. Learn the signs of Pitta imbalance — inflammation, irritability, burnout — and exactly how to bring it back into balance.",
    content: ``,
  },
  {
    slug: "vata-dosha-guide",
    category: "article",
    title: "Vata Dosha: Signs You're Out of Balance and What To Do About It",
    date: "May 15, 2026",
    excerpt: "I used to think anxiety was just my personality. Then I got my dosha assessment and the practitioner said: 'Classic Vata imbalance.' Everything had a name — and a remedy.",
    seoTitle: "Vata Dosha: Signs You're Out of Balance and How to Fix It",
    seoDescription: "Vata dosha governs movement, creativity, and the nervous system. Learn the signs of Vata imbalance — anxiety, dry skin, insomnia — and exactly how to bring it back into balance.",
    content: ``,
  },
  {
    slug: "ayurvedic-herbs-guide",
    category: "article",
    title: "The Ayurvedic Herb Guide: What's Actually in These Formulas and Why",
    date: "May 28, 2026",
    excerpt: "I'm sitting in a pharmacy that's been operating for over 200 years. Here's what I learned about the herbs that show up in every Ayurvedic formula — and why they work.",
    seoTitle: "Ayurvedic Herbs: A Practical Guide to Ashwagandha, Triphala, Brahmi & More",
    seoDescription: "A practical guide to the most important Ayurvedic herbs — what they do, the evidence behind them, and how to match them to your dosha type.",
    content: ``,
  },
]

export function getPostBySlug(slug: string): Post | undefined {
  return posts.find((post) => post.slug === slug)
}

export function getAllPosts(): Post[] {
  return posts
}
